pipeline {
    agent any

    parameters {
        // GitHub  사용자명 입력
        string(name: 'GITHUB_USERNAME',  defaultValue: 'hw9106', description: 'GitHub  사용자명을 입력하세요.')
    }	
    environment {
          
        GITHUB_SCRIPT_URL = "https://github.com/${GITHUB_USERNAME}/kubernetes-guest-script.git"
         //deployment.yaml -> image: academyitwill/guest:v1
         //실습 step 번호 - (수정x)
        STEP_NUM = 'step24'
    }

    stages {
        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                        extensions: [[$class: 'SparseCheckoutPaths',
                                      sparseCheckoutPaths: [[path: "/${STEP_NUM}"]]]],
                        userRemoteConfigs: [[url: "${GITHUB_SCRIPT_URL}"]])
            }
        }

       stage('쿠버네티스 Blue배포') {
            steps {
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/namespace.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/service.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/deployment.yaml"
            }
        }

        stage('자동배포 시작') {
            steps {
                input message: '자동배포 시작', ok: "Yes"
            }
        }

        stage('쿠버네티스 Green배포') {
            steps {
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/green/deployment.yaml"
            }
        }
        stage('Green 배포 확인중') {
            steps {
                script {
                    def returnValue
                    while (returnValue != "true true"){
                        returnValue = sh(returnStdout: true, encoding: 'UTF-8', script: "kubectl get -n guest-namespace-step24 pods -l name='guest',blue-green-no='2' -o jsonpath='{.items[*].status.containerStatuses[*].ready}'")
                        echo "${returnValue}"
                        sleep 5
                    }
                }
            }
        }

        stage('Green 전환 완료') {
            steps {
                sh "kubectl patch -n guest-namespace-step24 svc  guest-service -p '{\"spec\": {\"selector\": {\"blue-green-no\": \"2\"}}}'"
            }
        }

        stage('Blue 삭제') {
            steps {
                sh "kubectl delete -f ./${STEP_NUM}/deploy/k8s/blue/deployment.yaml"
                sh "kubectl patch -n guest-namespace-step24 svc guest-service -p '{\"metadata\": {\"labels\": {\"version\": \"2.0.0\"}}}'"
            }
        }
    }
}